app = "diabetes-cribado"
primary_region = "mad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"

